Отчет по практике.
Название: Калькулятор.
Причина выбора: Данное ПО имеет множество багов.
Ссылка на первоначальный репозиторий: https://github.com/parthwce/Project2025.git
### Баг № 1

**Описание**: Неправильное название функции вычитания

**Шаги воспроизведения**:
1. Запустить ПО
2. Ввести числа 

**Ожидаемое поведение**: Функция записана: Subtract

**Фактическое поведение**: Функция записана: Substract
**Серьёзность**: Средняя, работе не мешает, но является грубой ошибкой


### Баг № 2

**Описание**: Вместо функции вычитания выполняется сложение

**Шаги воспроизведения**:
1. Запустить ПО
2. Ввести числа 
3. Проверить операцию вычитания

**Ожидаемое поведение**: Выполняется вычитание чисел

**Фактическое поведение**: Выполняется повторное сложение чисел
**Серьёзность**: Высокая



### Баг № 3

**Описание**: Ошибки при делении на ноль

**Шаги воспроизведения**:
1. Запустить ПО
2. Ввести числа, второе число должно быть 0


**Ожидаемое поведение**: Калькулятор сам пишет свою ошибку о том, что введен 0 

**Фактическое поведение**: Выдается множество системных ошибок, так как происходит деление, которое приводит к сбою
**Серьёзность**: Высокая

### Баг № 4

**Описание**: Вызов substract вместо subtract в main:
**Шаги воспроизведения**:
1. Запустить ПО
2. Ввести числа


**Ожидаемое поведение**: Программа понимает, что нужно вывести и делает это без ошибок
**Фактическое поведение**: Программа не понимает, что ей нужно выполнить, так как функция записана неправильно 

**Серьёзность**: Высокая

### Баг № 5

**Описание**: Неинформативные подсказки ввода 

**Шаги воспроизведения**:
1. Запустить ПО
2. Ввести числа

**Ожидаемое поведение**: Программа может вычислять числа с плавающей точкой **Фактическое поведение**: Если пользователь случайно введет число с плавающей точкой (например, 3.14), это приведет к ValueError. Программе не хватает обработки ввода для обеспечения ввода чисел с плавающей точкой.

**Серьёзность**: Высокая

### Тест: Название функции

**Описание теста**: Проверяем правильность названия функции вычитания

**Шаги**:
1. Запустить ПО
2. Ввести число и проверить вывод

**Результат до исправления**: Не прошёл. Неправильное название функции, с ошибкой.
**Код до исправления**:
```py
def substract(a, b):   
    return a + b  
print("Subtraction:", substract(x, y))   

```

**Исправление**: Заменила название функции на правильное

**Код после исправления**:
```py
def subtract(a, b):   
    return a + b 
 print("Subtraction:", subtract(x, y)) 

```

**Результат после исправления**: Прошёл. Функция записана верно.
        

### Тест: Неправильная логика в subtract

**Описание теста**: Вместо операции вычитания выполняется сложение.
**Шаги**:
1. Запустить ПО
2. Ввести число и проверить вывод

**Результат до исправления**: Не прошёл. Вместо вычитания выполняется сложение.
**Код до исправления**:
```py
def subtract(a, b):   
    return a + b 

```

**Исправление**: Заменила действие на вычитание

**Код после исправления**:
```py
def subtract(a, b):   
    return a - b 

```

**Результат после исправления**: Прошёл. Выполняется нужное действие.

### Тест: Отсутствие обработки деления на ноль

**Описание теста**: Система дает сбой при делении на 0
**Шаги**:
1. Запустить ПО
2. Ввести число и проверить вывод

**Результат до исправления**: Не прошёл. Система выдает ошибки при делении на 0
**Код до исправления**:
```py
def divide(a, b):
    return a / b   

```

**Исправление**: Добавила вывод ошибки, убрала тем самым сбой в системе

**Код после исправления**:
```py
def divide(a, b):
    if b == 0:
        return "Error: Division by zero!"  
    return a / b

```

**Результат после исправления**: Прошёл. Выполняется вывод ошибки при делении на 0.

### Тест: Отсутствие валидации ввода: ValueError при вводе нецелого числа.
**Описание теста**: Система дает сбой при вводе числа с плавающей точкой
**Шаги**:
1. Запустить ПО
2. Ввести число с плавающей точкой и проверить вывод

**Результат до исправления**: Не прошёл. Система выдает ошибки при действиях с числами с плавающей точкой
**Код до исправления**:
```py
def add(a, b):
    return a + b

def subtract(a, b):   
    return a - b       
def multiply(a, b):
    return a * b

def divide(a, b):
    if b == 0:
        return "Error: Division by zero!"  
    return a / b

def main():
    print("Simple Calculator")
    x = int(input("Enter first number: "))
    y = int(input("Enter second number: "))

    print("Addition:", add(x, y))
    print("Subtraction:", subtract(x, y)) 
    print("Multiplication:", multiply(x, y))
    print("Division:", divide(x, y))       
if __name__ == "__main__":
    main()


```

**Исправление**: Добавила возможность работы с цифрами с плавающей точкой.

**Код после исправления**:
```py

def add(a, b):
    return a + b

def substract(a, b):   
    return a + b     

def multiply(a, b):
    return a * b

def divide(a, b):
    return a / b   

def main():
    print("Simple Calculator")
    
    while True:  
        try:
            x = float(input("Enter first number: "))  
            break  
        except ValueError:
            print("Invalid input. Please enter a number.")
    
    while True:  
        try:
            y = float(input("Enter second number: "))  
            break  
        except ValueError:
            print("Invalid input. Please enter a number.")

    print("Addition:", add(x, y))
    print("Subtraction:", substract(x, y))   
    print("Multiplication:", multiply(x, y))
    print("Division:", divide(x, y))         
if __name__ == "__main__":
    main()
```

**Результат после исправления**: Прошёл. Выполняются действия с числами с плавающей точкой
